"""add_application_date_to_job_offer

Revision ID: c60716ba2504
Revises: ce851e16fa1c
Create Date: 2026-05-19 06:32:39.296051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c60716ba2504'
down_revision: Union[str, None] = 'ce851e16fa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'website')
    op.add_column('job_offers', sa.Column('application_date', sa.DateTime(), nullable=False))
    op.alter_column('job_offers', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_offers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_job_offers_title', table_name='job_offers')
    op.create_index(op.f('ix_job_offers_application_date'), 'job_offers', ['application_date'], unique=False)
    op.drop_column('job_offers', 'applied_at')
    op.drop_column('job_offers', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_offers', sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_job_offers_application_date'), table_name='job_offers')
    op.create_index('ix_job_offers_title', 'job_offers', ['title'], unique=False)
    op.alter_column('job_offers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_offers', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('job_offers', 'application_date')
    op.add_column('companies', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
